name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]
    types: [opened]
  issues:
    types: [opened]
  push:
    branches: [master]

jobs:
  # Greeting the new contributer when they make a pull request or creat a issue
  greeting-contributers:
    runs-on: ubuntu-latest
    steps:
      - name: Greet new contributers
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = "Welcome to the Recetopia repository. Thank you for contributing!!!";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
        if: github.event_name == 'pull_request' || github.event_name == 'issues'

  # Assigning the pull requests and issues to the repo owner
  assign-to-owner:
    runs-on: ubuntu-latest
    steps:
      - name: Assign any pull request and issues to the owner of the repository
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
              assignees: [context.repo.owner]
            });
        if: github.event_name == 'pull_request' || github.event_name == 'issues'

  # Building the application, build the Docker container and push it to docker
  build-and-containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Installing the dependencies
        run: npm install

      - name: Build the React App
        run: npm run build

      - name: Build the Docker image
        run: |
          docker build -t recetopia .
          docker tag recetopia:latest docker.io/zack1808/recetopia:latest

      - name: Push Docker iamge to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin
          docker push docker.io/zack1808/recetopia:latest
